---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 200
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: argocd-terraform-controller-controller-manager
  namespace: argocd
status:
  availableReplicas: 1
  readyReplicas: 1
